#!/usr/bin/env python3
import sys

HEARTS = 10
STATUS_SYM = { 'Charging': '🗲' }

def vread(end):
    def vread_f(what):
        return float(
            open("/sys/class/power_supply/%s/%s" % (end, what), 'r').read()
        )

    try:
        maxv = vread_f('charge_full')
        curv = vread_f('charge_now')
    except IOError:
        maxv = vread_f('energy_full')
        curv = vread_f('energy_now')

    return curv / maxv

def sread(end):
    return open("/sys/class/power_supply/%s/status" % (end,)).read().strip()

def hearts(count):
    FULL = round(count * HEARTS)
    EMPTY = HEARTS - FULL

    hearts=''
    for _ in range(0, FULL):
        hearts += "♥ "
    for _ in range(0, EMPTY):
        hearts += "♡ "

    return hearts

def status(status):
    if status in STATUS_SYM:
        return STATUS_SYM[status]

if '--html' in sys.argv:
    print(('<span color="red">%s</span>'
          + '<span color="yellow">%s</span>')
          % (hearts(vread("BAT0")), status(sread("BAT0"))))
else:
    print(hearts(vread("BAT0")) + status(sread("BAT0")))
