#!/usr/bin/env python

import sys
import json
import SOAPpy

changes = json.load(sys.stdin)

for fil in changes['Files'].split("\n"):
    if fil == "":
        continue
    fp = fil.split()[4]
    print fp
