#!/usr/bin/env python

import urllib2
import json
import sys
import re

def check_url(url, type):
    try:
        u = urllib2.urlopen(url)
        print "I: PT: %s URL is OK (%s)" % (
            type,
            url
        )
    except urllib2.URLError as e:
        code = e.reason
        print "E: PT: %s URL is BAD! (%s) - %s" % (
            type, url, code
        )
    except urllib2.HTTPError as e:
        code = e.code
        print "E: PT: %s URL is BAD! (%s) - %s" % (
            type, url, code
        )

control = json.load(sys.stdin)
descrip = control['Description']
short = descrip.split('\n')[0]
src = control['Package']
print "I: PT: Does this sound right? \"%s is/are a(n) %s\"" % (
    src,
    short
)

check_url(control['Homepage'], 'homepage')
