#!/bin/bash

git branch >/dev/null 2>&1
RET=$?
STATUS=$(cat /sys/class/power_supply/BAT0/status)

if [ $RET -eq 0 ]; then
    echo -n "⎇  "
	git branch --color=never | grep \* | sed s/^*\ //
else
    #case $STATUS in
    #    Full)
    echo -n "⌚ "
    date "+%I:%M %p"
    #        ;;
    #    Discharging)
    #        echo -e -n "\e[31;1m"
    #        echo -n $(bheart)
    #        echo -e -n "\e[0m "
    #        ;;
    #    Charging)
    #        echo -e -n "\e[31;1m"
    #        echo -n $(bheart)
    #        echo -e -n "\e[0m "
    #        ;;
    #    *)
    #        echo -n "⌚ "
    #        date "+%I:%M %p"
    #        ;;
    #esac

fi
