#!/usr/bin/env python

import sys

colors = {
    "E:": "01;38;5;160",
    "W:": "40;33;01",
    "I:": "00;38;5;135",
    "P:": "01;38;5;157",
    "X:": "00;38;5;238"
}

lines = sys.stdin.readlines()
for line in lines:
    flag = line.strip()[:2].upper()
    reset = False
    if flag in colors:
        reset=True
        sys.stdout.write("[%sm" % (
            colors[flag]
        ))
    print line.strip()
    if reset:
        sys.stdout.write("[0m")
