#!/usr/bin/env python

import time
import urllib
import json

service = "http://pault.ag:8080/tail"
lastts  = 0

def loop():
	global lastts
	while True:
		f = urllib.urlopen("%s?since=%s" % (service, str(lastts)))
		msgs = json.loads(f.read())
		for x in msgs['messages']:
			print x['text']
			if lastts < x['timestamp']:
				lastts = x['timestamp']


loop()
