#!/usr/bin/env python

import sys
import json
import SOAPpy

url = 'http://bugs.debian.org/cgi-bin/soap.cgi'
namespace = 'Debbugs/SOAP'
server = SOAPpy.SOAPProxy(url, namespace)


changes = json.load(sys.stdin)

if not "Source" in changes:
    print "E: NO SOURCE NAME FOUND, BAD CHANGES"
    sys.exit(1)

src = changes['Source']

if "Closes" not in changes:
    print "I: %s source: This upload closes no bugs." % ( src )
    sys.exit(0)

bugs = changes['Closes'].split()
metainf = server.get_status(bugs)['item']

if len(bugs) <= 1:
    metainf = [ metainf ]

for bug in metainf:
    c_pkg = bug['value']['source']
    if not c_pkg: #metapkg?
        c_pkg = bug['value']['package']

    bno   = bug['value']['bug_num']

    if c_pkg != src:
        print "E: %s source: Bug #%s belongs to pkg %s, not %s" % (
            src, bno, c_pkg, src
        )
    else:
        print "I: %s source: Closes Bug #%s (which belongs to %s)" % (
            src, bno, src
        )
