#!/usr/bin/env python

import urllib2
import json
import sys


url = "https://github.com/users/%s/contributions_calendar_data"

who = sys.argv[1]

data = sorted([x[1] for x in json.loads(urllib2.urlopen(url % (who)).read())])
minimum = data[0]
maximum = data[-1]
total = len(data)
ctotal = 0

for num in data:
    ctotal += num

print "Over the last year, %s took %s actions on GitHub." % (who, ctotal)
print "Min: %s commits in a day" % (minimum)
print "Max: %s commits in a day" % (maximum)
print "Avg: %s commits / day" % (ctotal / total)
