#!/usr/bin/env python
# Copyright (c) 2012 Paul Tagliamonte <paultag@sunlightfoundation.com>
# under the terms of the LICENSE file

from __future__ import print_function
from sunlight import openstates

import json
import sys

print(json.dumps(openstates.legislator_detail(sys.argv[1])))

