#!/usr/bin/env python

import sys
import json

payload = {}

if len(sys.argv) > 1:
    f = open(sys.argv[1], 'r')
else:
    f = sys.stdin

lkh = None
lines = f.readlines()
for line in lines:
    if line[0] == " ":
        payload[lkh] += "\n" + line.strip()
    else:
        idex = line.index(":")
        lkh  = line[:idex].strip()
        line = line[idex + 1:].strip()
        payload[lkh] = line
print json.dumps(payload, sort_keys=True, indent=4)
