#!/usr/bin/env python

import json
import sys
import os

changes = json.load(sys.stdin)
files = changes['Files'].split("\n")
files.remove("")
for fil in files:
    inf = fil.split()
    deb = inf[4]
    ext = ".deb"
    if deb[-len(ext):] == ext:
        os.system("~/.bin/lint-deb %s" % deb)
