#!/usr/bin/env python

from sh import redshift
import json

location = json.load(open("/home/tag/.location.json", 'r'))
param = "%s:%s" % ( location['latitude'], location['longitude'] )
redshift( l=param )
