#!/usr/bin/python

import SOAPpy
import sys
from pbs import dget

url = 'http://bugs.debian.org/cgi-bin/soap.cgi'
namespace = 'Debbugs/SOAP'
server = SOAPpy.SOAPProxy(url, namespace)

look_for = "   dget"
last_cmd = None

log = server.get_bug_log(sys.argv[1])
for message in log:
    lines =  message['body'].split("\n")
    for line in lines:
        if line[:len(look_for)] == look_for:
            last_cmd = line.strip()

print "Guessed clone: "
print last_cmd
