#!/bin/bash
# Copyright (c) Paul Tagliamonte <paultag@ubuntu.com>, 2012, under the terms
# and conditions of the Expat license.

set -e

DIST="sid"
VARIANT="default"
SBUILD=/var/sbuild
#MIRROR="http://ftp.us.debian.org/debian"
MIRROR="http://mirrors.mit.edu/debian"

export `dpkg-architecture`

if [ "x$1" != "x" ]; then
    VARIANT=$1
fi
if [ "x$2" != "x" ]; then
    DIST=$2
fi

echo "I: "
echo "I: Dist:    $DIST"
echo "I: Variant: $VARIANT"
echo "I: "


if [ -e $SBUILD/$DIST.d/$DIST-$VARIANT  ]; then
    echo "E: Chroot already exists."
    exit 1
fi

echo "I: Running debootstrap. Please auth."
sudo debootstrap \
    --arch=$DEB_HOST_ARCH \
    --variant=buildd \
    --verbose \
    --include=fakeroot,build-essential \
    --components=main \
    --keyring=/etc/apt/trusted.gpg \
    --resolve-deps \
    --no-check-gpg \
    $DIST \
    $SBUILD/$DIST.d/$DIST-$VARIANT \
    $MIRROR

mkdir -p $SBUILD/$DIST.overlay.d/$DIST-$VARIANT
