#!/bin/bash
# Copyright (c) Paul Tagliamonte <paultag@ubuntu.com> under the terms and
# and conditions of sbuild it's self.

if [ "x$1" == "x" ]; then
    echo "Enter a dist (that's already present) to unmount"
    exit 1
fi

dist=$1

union_root="/srv/sbuild"

if [ "x`df -h $union_root/$dist | grep -v Filesystem | awk '{print $6}'`" \
    == "x/" \
]; then
    echo "Not mounted."
    exit 1
fi

echo "Press enter to unmount the $dist chroot."
read trash

sudo umount $union_root/$dist
