#!/bin/bash
# Copyright (c) Paul Tagliamonte <paultag@ubuntu.com> under the terms and
# and conditions of sbuild it's self.

if [ "x$1" == "x" ]; then
    echo "Enter a dist (that's already present) to mount"
    exit 1
fi

dist=$1

real_root="/var/sbuild"
union_root="/srv/sbuild"

if [ "x`df -h $union_root/$dist | grep -v Filesystem | awk '{print $6}'`" \
    != "x/" \
]; then
    echo "Please unmount *any* filesystems on $union_root/$dist, please."
    exit 1
fi

if [ ! -d $real_root/$dist ]; then
    echo "It appears you don't have the sbuild chroot created"
    echo " Expecting chroot at $real_root/$dist."
    exit 2
fi
if [ ! -d $union_root/$dist ]; then
    echo "It appears you don't have a union mount point."
    echo " Expecting empty folder at $union_root/$dist."
    exit 4
fi
if [ "x`find $union_root/$dist 2>&1`" != "x$union_root/$dist" ]; then
    echo "It looks like your union mount point has something in it."
    echo " Expecting an empty folder at $union_root/$dist"
    exit 5
fi

echo "Mounting $dist for action. Press enter if this is OK."
read trash

sudo mount -o bind    \
    $real_root/$dist  \
    $union_root/$dist
