#!/usr/bin/env python

from pbs import chromium_browser
from lxml import html
import urllib2
import sys

URL = "http://qa.debian.org/developer.php?login=%s"
OUT = "https://buildd.debian.org/status/package.php?p=%s&suite=sid&compact=compact"

uid = sys.argv[1]

url = URL % (uid)
f = urllib2.urlopen(url)
page = html.fromstring(f.read())
page.make_links_absolute(url)

packages = page.xpath("//table[@class='packagetable sortable']")
if packages == []:
    print "OMGWTFBBQ"
    sys.exit(1)

maint = packages[0]
packages = maint.xpath(".//tr/td//span/a")
names = [x.text_content() for x in packages]

chromium_browser(OUT % ('%2C'.join(names)))
